-- AlterTable
ALTER TABLE "Auction" ALTER COLUMN "brand" SET DATA TYPE TEXT,
ALTER COLUMN "model" SET DATA TYPE TEXT,
ALTER COLUMN "build_year" DROP NOT NULL,
ALTER COLUMN "build_year" SET DATA TYPE TEXT;
