import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "~/trpc/react";
import LoadingPage from "./_components/ui/LoadingPage";
import { Providers } from "./providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const locales = ['en', 'de', 'fr'];

export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}
export const metadata = {
  title: "Carnet",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}  bg-gray-50`}>
          <TRPCReactProvider headers={headers()}>
            <Providers>
              <ClerkLoading>
                <LoadingPage />
              </ClerkLoading>
              <ClerkLoaded>{children}</ClerkLoaded>
            </Providers>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
