import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { enUS, frFR, nlBE } from "@clerk/localizations";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { locales } from "~/config";
import { TRPCReactProvider } from "~/trpc/react";
import LoadingPage from "../_components/ui/LoadingPage";
import { Providers } from "../providers";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
export const metadata = {
  title: "Carnet",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: (typeof locales)[number] };
}) {
  unstable_setRequestLocale(locale);

  const messages = await getMessages();
  const internalization = {
    en: enUS,
    fr: frFR,
    nl: nlBE,
  };
  return (
    <html lang={locale}>
      <body className={`font-sans ${inter.variable}  bg-gray-50`}>
        <ClerkProvider localization={internalization[locale || "en"]}>
          <TRPCReactProvider headers={headers()}>
            <Providers>
              <ClerkLoading>
                <LoadingPage />
              </ClerkLoading>
              <ClerkLoaded>
                <NextIntlClientProvider locale={locale} messages={messages}>
                  {children}
                </NextIntlClientProvider>
              </ClerkLoaded>
            </Providers>
          </TRPCReactProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}

export const dynamic = "force-dynamic";
